"""comment

Revision ID: 055db429baef
Revises: 1fb0ecd2f542
Create Date: 2024-03-11 13:15:08.887871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055db429baef'
down_revision = '1fb0ecd2f542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('departure', sa.VARCHAR(length=100), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), nullable=False),
    sa.Column('distance', sa.FLOAT(), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('waypoint')
    # ### end Alembic commands ###
