"""comment

Revision ID: 1fb0ecd2f542
Revises: ac64e6211833
Create Date: 2024-03-07 01:15:31.787628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb0ecd2f542'
down_revision = 'ac64e6211833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps')
    # ### end Alembic commands ###
