"""empty message

Revision ID: 2da85f4ca6e6
Revises: a04b226c4134
Create Date: 2024-03-20 23:47:32.030747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da85f4ca6e6'
down_revision = 'a04b226c4134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('init_latitude', sa.Float(), nullable=False),
    sa.Column('init_longitude', sa.Float(), nullable=False),
    sa.Column('goal_latitude', sa.Float(), nullable=False),
    sa.Column('goal_longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('journey')
    # ### end Alembic commands ###
