"""updating a new field for subscription

Revision ID: 5fa53c44ac4e
Revises: c049842f319d
Create Date: 2024-03-08 12:09:50.308963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa53c44ac4e'
down_revision = 'c049842f319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_plan_change', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_subscription', schema=None) as batch_op:
        batch_op.drop_column('pending_plan_change')

    # ### end Alembic commands ###
