"""path

Revision ID: 678db78ee44e
Revises: 2da85f4ca6e6
Create Date: 2024-03-24 09:26:23.075037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678db78ee44e'
down_revision = '2da85f4ca6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filepath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('image_file_path', sa.String(), nullable=False),
    sa.Column('gpx_file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filepath')
    # ### end Alembic commands ###
