"""db

Revision ID: 77f6b6559c45
Revises: 678db78ee44e
Create Date: 2024-03-24 09:48:38.030102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f6b6559c45'
down_revision = '678db78ee44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Float(), nullable=False))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('arrival', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('arrival')
        batch_op.drop_column('departure')

    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###
