"""refactory

Revision ID: b8c8af8d661f
Revises: fd1b68a07acd
Create Date: 2024-03-25 04:04:56.130284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c8af8d661f'
down_revision = 'fd1b68a07acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
